import { type NextPage } from "next";
import Head from "next/head";
import Products from "~/components/products";
import Link from 'next/link';
import NavBar from "~/components/navbar";



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
<h1 className="font-bold text-5xl text-black">E-Commerce</h1>
<Products/>


        <ul className="flex justify-center gap-4 mt-6">
          <Link className="font-semibold text-black" href="/">Home
</Link>
          <Link className="font-semibold text-black" href="/add-product">Add Product
</Link>

          

        </ul>

      </main>
    </>
  );
};

export default Home;

