import { type NextPage } from "next";
import Head from "next/head";
import Products from "~/components/products";
import Link from 'next/link';



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
<h1 className="text-white font-bold text-5xl">E-Commerce</h1>
<Products/>
<header className="">
        <ul className="flex justify-center gap-4">
          <Link className="text-white font-semibold" href="/">Home
</Link>
          <Link className="text-white font-semibold" href="/add-product">Add Product
</Link>

          

        </ul>
      </header>
      </main>
    </>
  );
};

export default Home;

